spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cinema_reservation}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
